C_source := main.c vga.c uart.c console.c panic.c kalloc.c gdt.c irq.c idt.c isr.c speaker.c timer.c keyboard.c #memory.c
ASM_source := multiboot_entry_point.S descriptor_tables.S interrupt.S #paging.S
MODULE := kernel

include $(TOPDIR)/Makefile.inc